### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by declan393** [flowingsalt/BIM-Bot#5]
i tried to run it, and worked at least a week ago but as of 12/17/24 does not work and only throws an error

**Comment by flowingsalt** [comment]
Hey can you send me your discord? I can fix it with your account.

**Comment by declan393** [comment]
alr, but my school uses some sort of sso so im not sure how that world help

**Comment by declan393** [comment]
it is duckland_

**Comment by declan393** [comment]
btw this is what it says: 
polyfills.f7dc43f846…e7954fc.bundle.js:1 
 GET https://res.cloudinary.com/dq36xqdoe/raw/upload/v1679490768/BIM_gecfhv.js 401 (Unauthorized)

polyfills.f7dc43f846…e7954fc.bundle.js:1 Unhandled Promise rejection: Unexpected identifier 'dq36xqdoe' ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Unexpected identifier 'dq36xqdoe'
    at <anonymous>:1:130
    at t.invoke (polyfills.f7dc43f846…c.bundle.js:1:91265)
    at e.run (polyfills.f7dc43f846…c.bundle.js:1:86436)
    at polyfills.f7dc43f846…c.bundle.js:1:97542
    at t.invokeTask (polyfills.f7dc43f846…c.bundle.js:1:91949)
    at e.runTask (polyfills.f7dc43f846…c.bundle.js:1:87127)
    at v (polyfills.f7dc43f846…c.bundle.js:1:94185)
    at o (main.5d4244bce937741…undle.js:1:15614349)
    at main.5d4244bce937741…undle.js:1:15614471
    at MutationObserver.u (main.5d4244bce937741…undle.js:1:11700312) SyntaxError: Unexpected identifier 'dq36xqdoe'
    at <anonymous>:1:130
    at t.invoke (https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:91265)
    at e.run (https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:86436)
    at https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:97542
    at t.invokeTask (https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:91949)
    at e.runTask (https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:87127)
    at v (https://www.bigideasmath.com/MRL/public/app/polyfills.f7dc43f….bundle.js:1:94185)
    at o (https://www.bigideasmath.com/MRL/public/app/main.5d4244b….bundle.js:1:15614349)
    at https://www.bigideasmath.com/MRL/public/app/main.5d4244b….bundle.js:1:15614471
    at MutationObserver.u (https://www.bigideasmath.com/MRL/public/app/main.5d4244b….bundle.js:1:11700312)

**Comment by blazebal** [comment]
I’m having this problem too, i really hope it gets fixed
